language: bash

arch:
  - amd64
  - arm64

services:
  - docker

script:
  - ./build.sh
  -
    echo "$DOCKER_PASSWORD" |
    docker login -u "$DOCKER_USERNAME" --password-stdin
  -
    docker images --format "{{.Repository}}:{{.Tag}}" |
    awk '/akorn/ && !/none/' | tac | xargs -I {} docker push {}
